---
abstract: 'Plot your git commit history on the command line with sparklines'
author:
  - 'Eric Johnson <cpan at iijo dot nospamthanks dot org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Find: 0
  File::Spec::Functions: 0
  File::Temp: 0
  List::Util: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Git-Spark
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  App::Git::Spark:
    file: lib/App/Git/Spark.pm
    version: 0.006
requires:
  DateTime: 0
  Encode: 0
  Getopt::Long::Descriptive: 0
  List::AllUtils: 0
  Math::Round: 0
  Term::Spark: 0
  Term::Vspark: 0
  perl: 5.008
  strict: 0
  utf8: 0
  warnings: 0
resources:
  bugtracker: https://github.com/kablamo/git-spark/issues
  homepage: https://metacpan.org/release/App-Git-Spark
  repository: git://github.com/kablamo/git-spark.git
version: 0.006
x_contributors:
  - 'Eric Johnson <eric.git@iijo.org>'
